# Generated by Django 3.0.6 on 2020-05-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BTOPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTOResponsivePage',
            fields=[
                ('btopage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BTOPage.BTOPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('BTOPage.btopage',),
        ),
    ]
