# Generated by Django 3.0.6 on 2020-06-06 02:20

import BTOPage.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
        ('BTOPage', '0003_btopageinfosnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTOTopicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('author', models.CharField(blank=True, default='William D. Torcaso', max_length=64, null=True)),
                ('info_snippets', wagtail.core.fields.StreamField([('info_snippet', wagtail.snippets.blocks.SnippetChooserBlock(BTOPage.models.BTOInfoSnippet)), ('page_info_snippet', wagtail.snippets.blocks.SnippetChooserBlock(BTOPage.models.BTOPageInfoSnippet))], blank=True, null=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
