# Generated by Django 3.0.6 on 2020-06-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTOPage', '0004_btotopicpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btotopicpage',
            name='author',
        ),
        migrations.AddField(
            model_name='btotopicpage',
            name='topic',
            field=models.CharField(blank=True, default='Topic _____', max_length=64, null=True),
        ),
    ]
